using System.ComponentModel;
using System.Globalization;

namespace SatisfactoryPlanner;

/// <summary>
/// UI text translations. Game names (items, buildings, recipes, unlock text) come from the localized
/// wiki data instead — see GameData.Load. XAML binds with {Binding [key], Source={x:Static local:Loc.Instance}}
/// so switching language updates the window live.
/// </summary>
public class Loc : INotifyPropertyChanged
{
    public static Loc Instance { get; } = new();
    /// <summary>
    /// Languages offered: English, every language the local game install ships, plus the wiki's de/fr.
    /// Game names switch for all of them; the app's own UI text is translated for de, fr and zh-Hans (English otherwise).
    /// </summary>
    public static List<(string code, string name)> Languages { get; } = BuildLanguages();

    static List<(string code, string name)> BuildLanguages()
    {
        var codes = new List<string> { "en" };
        codes.AddRange(GameLocale.Languages());
        codes.AddRange(GameData.WikiLanguages.Select(w => w.lang));
        return codes.Distinct().Select(c => (c, c == "en" ? "English" : Native(c)))
            .OrderBy(l => l.c == "en" ? 0 : 1).ThenBy(l => l.Item2, StringComparer.CurrentCulture).ToList();
    }

    static string Native(string code)
    {
        try { var n = CultureInfo.GetCultureInfo(code).NativeName; return char.ToUpper(n[0]) + n[1..]; }
        catch (CultureNotFoundException) { return code; }
    }

    string _lang = "en";
    public string Language
    {
        get => _lang;
        set
        {
            _lang = Languages.Any(l => l.code == value) ? value : "en";
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item[]"));
        }
    }

    public string this[string key]
    {
        get
        {
            if (_lang.StartsWith("zh-Hans") && Zh.TryGetValue(key, out var zh)) return zh;
            if (!Table.TryGetValue(key, out var r)) return key;
            return (_lang == "de" ? r.de : _lang == "fr" ? r.fr : r.en) ?? r.en;
        }
    }

    public static string T(string key, params object[] args) =>
        args.Length == 0 ? Instance[key] : string.Format(CultureInfo.CurrentCulture, Instance[key], args);

    /// <summary>Default to the OS language when we have it (exact match first, e.g. zh-Hans, then the two-letter code).</summary>
    public static string DefaultLanguage()
    {
        var ui = CultureInfo.CurrentUICulture;
        foreach (var c in new[] { ui.Name, ui.Parent.Name, ui.TwoLetterISOLanguageName })
            if (Languages.Any(l => l.code.Equals(c, StringComparison.OrdinalIgnoreCase)))
                return Languages.First(l => l.code.Equals(c, StringComparison.OrdinalIgnoreCase)).code;
        return "en";
    }

    public event PropertyChangedEventHandler? PropertyChanged;

    /// <summary>Simplified Chinese UI text (terms follow the game's zh-Hans localization).</summary>
    static readonly Dictionary<string, string> Zh = new()
    {
        ["btn.update"] = "从 Wiki 更新数据和图标",
        ["btn.loadSave"] = "载入存档…",
        ["btn.forgetSave"] = "移除存档",
        ["save.label"] = "存档：{0} · 已解锁 {1} 个替代配方",
        ["save.tooltip"] = "仅使用该存档中已解锁的配方",
        ["save.dialogTitle"] = "打开 Satisfactory 存档",
        ["save.filter"] = "Satisfactory 存档 (*.sav)|*.sav",
        ["save.loaded"] = "已载入 {0}：{1} 个已解锁配方，第 {2} 阶段。",
        ["save.error"] = "无法读取存档：{0}",
        ["save.unsupported"] = "未找到已解锁配方列表——存档版本不受支持？",
        ["status.downloadingData"] = "正在从 satisfactory.wiki.gg 下载配方…",
        ["status.downloadingIcons"] = "正在下载图标… {0}",
        ["status.updated"] = "已更新：{0} 个配方，{1} 个图标。",
        ["status.updateFailed"] = "更新失败：{0}",
        ["status.iconsDownloaded"] = "已从 Wiki 下载 {0} 个图标。",
        ["status.iconsFailed"] = "图标不可用：{0}",

        ["grp.targets"] = "生产目标（每分钟）",
        ["btn.addProduct"] = "+ 添加产品",
        ["grp.recipeSel"] = "配方选择",
        ["opt.myPicks"] = "我的选择（默认 + 表格中替换的配方）",
        ["opt.minimal"] = "最少资源——在当前科技等级下寻找最佳配方组合（稀有矿石权重更高）。表格中替换的配方保持固定。",
        ["btn.clearPins"] = "清除固定 / 替换的配方",
        ["grp.tech"] = "科技进度",
        ["tier"] = "第 {0} 阶段",
        ["chk.alts"] = "包含替代配方（硬盘）",
        ["chk.mam"] = "包含 M.A.M. 研究配方",
        ["grp.nodes"] = "你拥有的资源节点",
        ["nodes.help"] = "按纯度填写节点数量（优先使用纯净节点）。留空 = 不限节点，按普通计算。“上限 /分”用于限制某种资源，例如传送带吞吐量。",
        ["col.limit"] = "上限",
        ["col.pure"] = "纯净",
        ["col.norm"] = "普通",
        ["col.imp"] = "贫瘠",
        ["col.resource"] = "资源",
        ["tip.untick"] = "如果暂时无法获取该资源，请取消勾选",
        ["needsTier"] = "（需第 {0} 阶段）",
        ["grp.extraction"] = "采集",
        ["lbl.miner"] = "采矿机",
        ["lbl.clock"] = "时钟速度",
        ["grp.rounding"] = "取整方式（一直追溯到采矿机）",
        ["mode.exact"] = "精确——允许小数台机器 / 降频",
        ["mode.steady"] = "稳定产量优先——超产。所有机器和采矿机按 100% 向上取整；产量 ≥ 目标，多余部分会堵塞。",
        ["mode.noclog"] = "不堵塞优先——欠产。采矿机向下取整，整条产线按比例降速；永远不会堵塞。",

        ["summary"] = "{0} 台机器   ·   {1:0.#} MW",
        ["summary.withExtractors"] = "{0} 台机器（含 {1} 台采矿机/采集设备）   ·   {2:0.#} MW",
        ["chk.countExtractors"] = "计入采矿机和采集设备",
        ["tab.table"] = "表格",
        ["tab.tree"] = "生产树",
        ["lbl.zoom"] = "缩放",
        ["btn.fit"] = "适应窗口",
        ["hint.tree"] = "Ctrl + 滚轮缩放 · 悬停方框只显示其连线 · 虚线 = 循环",
        ["tab.totals"] = "机器总计",
        ["col.type"] = "类型",
        ["kind.extractor"] = "采矿机 / 采集设备",
        ["kind.production"] = "生产",
        ["node.target"] = "最终产品",
        ["node.surplus"] = "富余 / 副产品",
        ["tabs.plan"] = "方案 {0}",
        ["tabs.copy"] = "{0}（副本）",
        ["tabs.new"] = "新建方案标签页",
        ["tabs.rename"] = "重命名…",
        ["tabs.renameTitle"] = "重命名方案",
        ["tabs.duplicate"] = "复制",
        ["tabs.duplicateActive"] = "复制当前方案（例如用来尝试其他配方）",
        ["tabs.close"] = "关闭",
        ["tabs.confirmClose"] = "关闭“{0}”？其生产目标和配方选择将被删除。",
        ["ok"] = "确定",
        ["cancel"] = "取消",
        ["mode.drained"] = "产出被持续取走——最终产品不断被运走（火车、回收站、储存），永远不会堵塞。每条共用传送带都会得到分流器布局（1 个分流器，允许时可串联 2 个，见“分流器”标签页）和足够的供应，确保最弱的产品也能达到目标。",
        ["out.headroom"] = "富余产能——会堵在传送带上，但不浪费",
        ["crash"] = "出了点问题，但你的方案没有丢失：\n\n{0}\n\n详细信息已保存到 {1}",
        ["tab.splitters"] = "分流器",
        ["col.supply"] = "供应 /分",
        ["col.extra"] = "额外",
        ["col.layout"] = "布局（⑂n = n 路分流器）",
        ["col.shares"] = "消耗方：需求 /分（份额）",
        ["split.none"] = "只有一个消耗方——无需分流器",
        ["split.manifold"] = "串联分流（每台机器一个分流器），{0} 放在最后",
        ["split.hint"] = "每条供给多个消耗方的传送带，以及分流器布局（1 个分流器，允许时可串联 2 个）和所需供应量，确保最弱的消耗方也能拿到全部需求。“额外”是贪婪分支（被持续取走的产出、向上取整的机器）超出需求多拿的部分。",
        ["split.onlyDrained"] = "分流器布局在“产出被持续取走”取整模式下规划（当最终产品被不断运走时）。",
        ["chk.twoSplitters"] = "允许串联 2 个分流器（默认 1 个）",
        ["kind.logistics"] = "传送带 / 管道部件",
        ["node.sink"] = "回收站 / 储存",
        ["split.smart"] = "智能分流器：{0} 接普通输出，{1} 接溢出（只接收机器吃不下的部分）",
        ["split.pipe"] = "管道串联（用管道接头；流体按需分配）",
        ["chk.endSplitter"] = "最后一台机器前也放分流器（为了美观）",
        ["tip.endSplitter"] = "串联末端的分流器没有实际作用，但让每台机器的输入看起来一致。每条串联多计 1 个分流器。",
        ["summary.logistics"] = "   ·   {0} 个分流器、{1} 个合并器、{2} 个管道接头",
        ["grp.belts"] = "传送带与分流器",
        ["lbl.belt"] = "传送带",
        ["lbl.pipe"] = "管道",
        ["belt.auto"] = "自动——本阶段已解锁的最佳",
        ["belt.current"] = "按 {0} 传送带和 {1} 管道规划；超出容量的物流会拆成多条并行线路。",
        ["col.line"] = "线路",
        ["col.belt"] = "传送带 / 管道",
        ["split.lines"] = "一条传送带装不下：拆成 {0} 条并行线路，每条由各自的机器供料",
        ["edge.belts"] = "×{0} 条 {1}",
        ["warn.notConverged"] = "产出持续取走模式：方案过大，分流器/供应平衡提前结束——请预留一些余量。",
        ["warn.machineOverBelt"] = "一台 {0} 需要 {1}/分，超过一条 {2} 的运量。请用 {3} 条传送带在机器前合并供料，或选择更快的传送带。",
        ["node.line"] = "线路 {0}/{1}",
        ["node.inLines"] = "分 {0} 条线路",
        ["btn.useSave"] = "使用存档",
        ["tip.useSave"] = "开：只用存档中已解锁的配方规划。关：忽略存档（仍保持载入），改用本标签页的阶段与替代/M.A.M. 设置——便于快速比较解锁更多科技的收益。",
        ["warn.notSettled"] = "产出持续取走模式：此方案的分流器/供应平衡未完全收敛——请预留一些余量。",
        ["tab.guards"] = "防堵塞",
        ["tab.guardsCount"] = "防堵塞（{0}）",
        ["tab.guardsWarn"] = "⚠ 防堵塞（{0} 处必需）",
        ["tab.guardsMixed"] = "⚠ 防堵塞（{0} 处必需，{1} 处已解决）",
        ["tab.guardsResolved"] = "✓ 防堵塞（全部 {0} 处已解决）",
        ["guard.hint"] = "多产出机器只要任一输出堵住就会完全停机。每条溢流都要有一个永远不会满的去处：AWESOME 回收站或发电机（箱子会满，输出也不保证有人取走）。加工后的产物也是溢流，会在下方单独一张卡片里继续处理。",
        ["guard.col.machine"] = "机器",
        ["guard.col.output"] = "输出",
        ["guard.col.level"] = "必要性",
        ["guard.col.device"] = "防护",
        ["guard.col.where"] = "位置 / 做法",
        ["guard.required"] = "必需",
        ["guard.recommended"] = "建议",
        ["guard.smart"] = "智能分流器（溢出）",
        ["guard.valve"] = "管道接头 + 阀门",
        ["guard.smartHow"] = "紧接在{0}的输出传送带后：{1} 接普通输出，溢出口接你的回收站/储存（约 {2:0.##}/分 溢出）。",
        ["guard.valveHow"] = "紧接在{0}的输出管道后：接一个管道接头；通往 {1} 的分支装阀门并设为 {2:0.##} m³/分，另一分支接你的回收站/储存（约 {3:0.##} m³/分 溢出）。",
        ["guard.recommendedWhy"] = "正常情况下不会溢出——当 {0} 堵住时保护这些机器。",
        ["guard.perLine"] = "每条线路一个（共 {0} 条）。",
        ["guard.badge"] = "溢出",
        ["guard.badgeTip"] = "需要溢出防护：{0}。见“防堵塞”标签页。",
        ["warn.clog"] = "{0} 个机器输出没有溢出防护会堵塞——见“防堵塞”标签页。",
        ["summary.valves"] = "、{0} 个阀门",
        ["guard.routeAway"] = "全部导出",
        ["guard.allAwayHow"] = "方案中没有机器使用它：把{0}的全部输出直接送往回收站/储存（约 {1:0.##} {2}）。无处可去时机器会停机。",
        ["tab.layout"] = "布局",
        ["btn.exportPng"] = "导出 PNG…",
        ["btn.exportCsv"] = "导出 CSV…",
        ["btn.exportBp"] = "导出蓝图…",
        ["tip.exportBp"] = "把布局写成游戏蓝图（每块一个，“标签名 r1c1”…），放进你选的文件夹——一般是 SaveGames\\blueprints 下该存档的文件夹。需要安装 Node.js。",
        ["bp.needTile"] = "请先选择蓝图尺寸（Mk2 / Mk3）：蓝图按块导出。",
        ["bp.noNode"] = "导出蓝图需要 Node.js，但没有找到它。\n\n要打开 nodejs.org 下载吗？（安装后重启本程序）",
        ["bp.noWriter"] = "找不到蓝图写入器：{0}",
        ["bp.pickFolder"] = "选择蓝图文件夹（SaveGames\\blueprints 下该存档的文件夹）",
        ["bp.noBase"] = "“{0}”里没有游戏里做的蓝图。\n\n蓝图需要该存档的信息：先在游戏里存一个任意蓝图到这个文件夹，再导出。",
        ["bp.writing"] = "正在写蓝图…",
        ["bp.checkNode"] = "正在检查 Node.js…",
        ["bp.installing"] = "首次导出：正在安装蓝图写入器（npm）…",
        ["bp.installFailed"] = "无法安装蓝图写入器（需要 npm 和网络）：{0}\n可改用“完整版”程序（自带全部组件，无需网络）。",
        ["bp.progress"] = "已写 {0} / {1} 个蓝图",
        ["bp.done"] = "已写入 {0} 个蓝图到 {1}",
        ["bp.summary"] = "已写入 {0} 个蓝图到：\n{1}\n\n块之间有 {2} 处接口需要手动连接，见“wiring.txt”。\n（存档信息取自 {3}）",
        ["bp.wiringHead"] = "{0}：块之间需要手动连接的传送带 / 管道（东、北方向，从西南角算起）",
        ["lbl.floors"] = "楼层：",
        ["lbl.showFloor"] = "显示：",
        ["floor.all"] = "全部",
        ["layout.busy"] = "正在计算布局…",
        ["lbl.blueprint"] = "蓝图",
        ["status.floor"] = "第 {0} / {1} 层：放置机器并布线",
        ["status.route"] = "放置机器并布线",
        ["status.reroute"] = "部分传送带放不下：给机器留出更多空间后重新布线",
        ["status.floorOf"] = "第 {0} / {1} 层",
        ["btn.advanced"] = "⚙ 高级 ▾",
        ["guard.col.how"] = "如何处理",
        ["lbl.legend"] = "图例",
        ["kpi.machines"] = "机器",
        ["kpi.machinesSub"] = "含 {0} 台采集设备",
        ["kpi.machinesNoExt"] = "不含 {0} 台采集设备",
        ["kpi.power"] = "电力",
        ["kpi.powerSub"] = "100% 频率时的用电",
        ["kpi.powerGen"] = "净用电，发电机发电 {0:0} MW",
        ["kpi.inputs"] = "原料输入（/分钟）",
        ["kpi.clog"] = "防堵塞",
        ["kpi.clogOpen"] = "{0} 处必需",
        ["kpi.clogOpenSub"] = "已解决 {0} 处，见“防堵塞”",
        ["kpi.clogAll"] = "全部已解决",
        ["kpi.clogAllSub"] = "{0} 条溢流都有安全去处",
        ["kpi.clogNone"] = "无需处理",
        ["kpi.clogNoneSub"] = "没有会堵住的多产出机器",
        ["hdr.overflow"] = "处理溢流的机器",
        ["clog.status.good"] = "✓ 安全",
        ["clog.status.next"] = "→ 下一步见下方",
        ["clog.status.warn"] = "⚠ 满了会堵",
        ["clog.status.info"] = "建议",
        ["hint.overflowRow"] = "处理溢流的机器：只能在“防堵塞”中修改（选择如何处理）。",
        ["tip.clogHow"] = "多余的产出怎么办：只有进 AWESOME 回收站或烧进发电机才永远不会堵（箱子会满，输出也不保证有人取走）。也可以加机器把它做成别的东西，但做出来的也是溢流，要在它自己的那一行继续处理；做成本计划的产品时可经智能分流器并入输出，溢流进回收站。",
        ["clog.box"] = "溢流进箱子（会装满，不安全）",
        ["clog.keep"] = "保持现状（机器会全部用掉）",
        ["clog.gen"] = "烧进{0}（每台 {1:0.#}/分钟，{2:0} MW）",
        ["clog.merge"] = "并入{0}的输出（智能分流器，溢流到 AWESOME 回收站）",
        ["clog.chain"] = "{2:0.##} {3} {0}：由 {1} 用多余产出做成，它本身也是溢流，需要自己的去处。",
        ["clog.boxHow"] = "现在溢流进箱子：箱子满了就会堵，整条链都会停。",
        ["clog.genHow"] = "溢流烧进发电机（发电机永远不会满）。",
        ["clog.mergeHow"] = "先经智能分流器：一路并入该产品的输出，溢流进 AWESOME 回收站，输出没人取走也不会堵。",
        ["item.overflow"] = "{0}（溢流）",
        ["clog.sink"] = "溢流进 AWESOME 回收站",
        ["clog.recipe"] = "→ {0}（{1} → {2}）",
        ["clog.sinkHow"] = "溢流端直接接到 AWESOME 回收站（智能分流器溢流）。",
        ["clog.recipeHow"] = "多余部分由 {0} 用掉，做出的东西是新的溢流，见下方卡片。",
        ["out.sink"] = "多余（溢流进 AWESOME 回收站）",
        ["loop.title"] = "塑料 + 橡胶：循环生产？",
        ["loop.ask"] = "这个计划只生产塑料和橡胶，你的配方也支持“回收循环”：\n\n原油 → 重油残渣（替代）→ 稀释包装燃料（替代，配合包装水）→ 解包燃料 → 回收塑料 / 回收橡胶互相转化。每 30 原油约得 80 塑料 + 橡胶（普通配方约 40）。\n\n需要一次性的启动库存：放一些塑料、橡胶到回收精炼厂，放一些空桶到包装机。智能分流器优先供给循环，只有多余的才送去输出，所以循环不会断。\n\n“是”：使用循环生产。\n“否”：使用普通配方（更简单，每单位原油产量更低）。",
        ["loop.seed"] = "回收循环：启动前放入塑料、橡胶（给回收精炼厂）和空桶（给包装机），之后循环会自行补充。",
        ["lbl.timeLimit"] = "布局计算时间上限",
        ["tip.timeLimit"] = "时间越长，大型计划越有机会得到布线布局。时间太短时，大型计划（多种机器、多层）很可能来不及，只能得到按行排列的布局。",
        ["layout.left"] = "剩余 {0}（上限 {1}）",
        ["layout.overtime"] = "时间到，正在收尾…",
        ["layout.fallback"] = "如果时间内找不到布线布局，将改用按行排列的简单布局（机器成行摆放，传送带更长，占地更大）。可在“⚙ 高级”中延长时间，再点“重新布局”。",
        ["status.stack"] = "堆叠 {0} 条拥挤通道",
        ["status.rows"] = "改用按行排列的布局",
        ["status.steps"] = "再试按生产步骤分层",
        ["chk.backUp"] = "中间产品可堆积（无副产品时不超产）",
        ["tip.backUp"] = "只供机器使用的中间产品允许在传送带上堆积：分流器会自行平衡，不需要额外供应。生产它的机器若有副产品则不适用（副产品堵塞会让机器停下，产量下降）。",
        ["status.narrow"] = "再试更紧凑的机器组",
        ["status.compact"] = "压缩布局（收拢空白）",
        ["status.twostage"] = "再试：先布短线，再让长线走上层",
        ["status.elapsed"] = "已用 {0} 秒",
        ["layout.handTag"] = "手动放置",
        ["bp.off"] = "不分块",
        ["bp.mk2"] = "Mk2（5×5）",
        ["bp.mk3"] = "Mk3（6×6）",
        ["chk.byHand"] = "机器可跨块（手动放置）",
        ["hand.warn"] = "机器可跨块模式：蓝图可能放不整齐。\n\n• 跨块的机器不在蓝图里，需要你手动放置（✋ 标记）。\n• 块边界附近没有保护区：靠近边界的传送带 / 管道、分流器、合流器和坡道可能被边界截断、错位或需要手动补完（见 wiring.txt 的“手动连接”）。\n• 分流器 / 合流器可能离弯道太近，出口歪斜。\n\n一般能省蓝图，但需要更多手动修整。继续吗？",
        ["chk.bigTank"] = "工业流体缓冲器",
        ["tip.bigTank"] = "流体的输入 / 输出箱使用工业流体缓冲器（2400 m³，约 12 米宽），而不是流体缓冲器（400 m³，4 米）。布局会更大（塑料工厂实测 4 → 7 张蓝图）。",
        ["cache.bigTank"] = "工业缓冲器",
        ["tip.byHand"] = "允许机器跨越蓝图边界：这些机器不放进蓝图，由你手动放置。同组中只要有一台在蓝图内，其余按它对齐；整组都需手动放置时，该组的角点必须在地基角上。⚠ 边界附近的传送带 / 管道可能被截断或错位，需要手动修整。",
        ["layout.byHand"] = "{0} 台机器需手动放置",
        ["lbl.cached"] = "已存布局",
        ["tip.cached"] = "此标签页已算好的布局，连同各自的计划（↩ 为其他计划）。选一个即恢复它的计划与布局选项，无需重新计算。",
        ["btn.relayout"] = "重新布局",
        ["tip.relayout"] = "忽略已存的布局，重新计算（并替换它）。",
        ["layout.fromCache"] = "已存布局",
        ["cache.blueprints"] = "{0} 张蓝图 · ",
        ["cache.machines"] = "{0} 台机器",
        ["cache.entry"] = "{0} 层 · {1}{2} · {3}{4:0} 米 · {5:M/d HH:mm}",
        ["layout.openAbove"] = "上方不铺地基（{0} 穿过此层）",
        ["layout.copies"] = "模块：此布局放置 {0} 次（每个 1/{0} 产量）",
        ["layout.info"] = "{0:0} × {1:0} 块地基（{2:0} × {3:0} 米）· {4} 排 · {5} 条总线",
        ["layout.legend"] = "俯视图，北向上；每次显示一层（“显示”），其他楼层为虚线轮廓。每排机器组：输入从南侧传送带进入（白方块 = 分流器），输出从北侧传送带离开（空心方块 = 合并器）。每种物品有一条竖直主干，放在其机器旁；箭头表示流向。车站箱位于最底排东端，外侧保持空出：绿 = 输入，紫 = 输出，灰 = 富余/溢出。⊕ = 每组的角锚点（位于地基角上）。虚线 + 橙色端点 = 升高越过其他传送带或机器（不越过高于 12 米的机器）。紫色方块 ⇅ = 通往其他楼层的升降机/管道。层高 12 米，若有高于 11 米的机器则 16 米；高于 15 米的建筑只放在顶层。红 = 防堵塞。尺寸：satisfactory-calculator.com，高度：satisfactory.wiki.gg。",
        ["layout.saved"] = "已保存 {0}",
        ["layout.anchor"] = "⊕ 角锚点在地基 ({0:0}, {1:0})，之后每隔 {2:0} 米",
        ["layout.anchor2"] = "⊕ {0} 角在地基 ({1:0}, {2:0})，之后每隔 {3:0} 米",
        ["layout.belts"] = " · 传送带与管道约 {0:0} 米 · 每排最多 {1} 台机器",
        ["summary.scale"] = "   ·   实际产量为目标的 {0:P1}",
        ["error"] = "错误：{0}",
        ["hint.production"] = "生产——在“配方”列中选择其他配方即可替换。",
        ["col.item"] = "物品",
        ["col.recipe"] = "配方",
        ["col.building"] = "建筑",
        ["col.machines"] = "机器数",
        ["col.clock"] = "频率",
        ["col.output"] = "产出 /分",
        ["col.inputs"] = "输入 /分",
        ["col.goesTo"] = "流向 /分",
        ["col.power"] = "功率 MW",
        ["hdr.raw"] = "原材料与采集设备",
        ["col.rate"] = "速率 /分",
        ["col.extractor"] = "采集设备",
        ["col.count"] = "数量",
        ["col.note"] = "备注",
        ["tab.outputs"] = "产出与副产品",
        ["col.outputItem"] = "产出",
        ["col.perMin"] = "/分",
        ["tab.unlock"] = "解锁建议",
        ["tab.unlockCount"] = "解锁建议（{0}）",
        ["tab.unlockWarn"] = "⚠ 解锁建议",
        ["col.benefit"] = "收益",
        ["col.unlockedBy"] = "解锁方式",
        ["analysing"] = "分析中…",
        ["analysisFailed"] = "分析失败：{0}",

        ["alt"] = "替代：",
        ["purity.Pure"] = "纯净",
        ["purity.Normal"] = "普通",
        ["purity.Impure"] = "贫瘠",
        ["goes.target"] = "{0} 目标",
        ["import"] = "外部输入",
        ["note.noRecipe"] = "没有已解锁的配方（或产量不足）——需从外部运入",
        ["note.supplied"] = "运入（在别处生产，像原料一样送来）",
        ["recipe.import"] = "📦 改为运入（在别处生产）",
        ["imp.label"] = "运入：",
        ["grp.imported"] = "运入的物品（在别处生产）",
        ["tip.import"] = "本计划不生产这些物品，而是像原料一样从别处运入（例如独立的塑料 / 橡胶工厂）。本工厂要生产的产品不会被当作运入。",
        ["tip.unimport"] = "改回在本工厂生产",
        ["tip.importPick"] = "输入名称搜索，添加一个运入的物品",
        ["tip.productSearch"] = "输入名称的任意部分搜索（中文或英文），回车或点击即可添加为产品",
        ["chk.polymers"] = "塑料和橡胶作为原料运入",
        ["tip.polymers"] = "不在此工厂生产塑料 / 橡胶（省去两者互相循环的炼油链），从外部运入。它们是本方案的产品时仍会生产。",
        ["why.tier"] = "采集设备需第 {0} 阶段",
        ["why.marked"] = "已标记为无法获取",
        ["note.notAccessible"] = "无法获取（{0}）——需运入或更换配方",
        ["warn.notAccessible"] = "需要 {0}，但无法获取（{1}）。",
        ["warn.overLimit"] = "{0}：需要 {1}/分，但你的节点/上限只能提供 {2}/分。",
        ["warn.lessThanOne"] = "{0}：需求不足一台完整的采集设备——改为降频运行。",
        ["note.short"] = "缺少 {0}/分——填写的节点不够",
        ["note.spare"] = "+{0}/分 富余供应（会堵塞）",
        ["note.underclock"] = "降频以免堵塞",
        ["out.target"] = "目标 {0}/分",
        ["out.actual"] = " → 实际 {0}",
        ["out.byproduct"] = "副产品 / 富余（送入回收站或储存）",
        ["warn.loop"] = "你选择的配方形成了循环；已用优化器在相同配方下完成平衡。",
        ["warn.deficit"] = "{0}：产量不足——需外部输入 {1:0.##}/分。",
        ["warn.noConverge"] = "优化器未能收敛——无结果。",
        ["warn.cantMake"] = "{0}：{1:0.##}/分 无法用当前科技/资源生产——需外部输入。",

        ["unlock.notPossible"] = "第 {0} 阶段无法实现：{1} 无法生产",
        ["unlock.untilTier"] = "，需达到第 {0} 阶段里程碑。",
        ["unlock.checkResources"] = "（请检查可获取的资源）。",
        ["unlock.required"] = "必需——用于生产 {0}",
        ["unlock.requiredSummary"] = "请解锁 {0} 个必需配方以生产 {1}。",
        ["unlock.saves"] = "可选——节省 {0:P1} 原材料",
        ["unlock.combined"] = "可选——与其他配方组合时有帮助",
        ["unlock.optionalSummary"] = "解锁第 {1} 阶段可用的 {0} 个可选配方，可节省 {2:P1} 的加权原材料。",
        ["unlock.nothing"] = "无需解锁——你的配方已是第 {0} 阶段的最佳方案。",
    };

    static readonly Dictionary<string, (string en, string? de, string? fr)> Table = new()
    {
        // top bar
        ["btn.update"] = ("Update data & icons from wiki", "Daten & Symbole aus dem Wiki aktualisieren", "Mettre à jour données & icônes depuis le wiki"),
        ["btn.loadSave"] = ("Load save file…", "Spielstand laden…", "Charger une sauvegarde…"),
        ["btn.forgetSave"] = ("Forget save", "Spielstand entfernen", "Oublier la sauvegarde"),
        ["save.label"] = ("Save: {0} · {1} alts unlocked", "Spielstand: {0} · {1} Alternativen freigeschaltet", "Sauvegarde : {0} · {1} alternatives débloquées"),
        ["save.tooltip"] = ("Using exactly the recipes unlocked in the loaded save", "Verwendet genau die im Spielstand freigeschalteten Rezepte", "Utilise exactement les recettes débloquées dans la sauvegarde"),
        ["save.dialogTitle"] = ("Open Satisfactory save", "Satisfactory-Spielstand öffnen", "Ouvrir une sauvegarde Satisfactory"),
        ["save.filter"] = ("Satisfactory save (*.sav)|*.sav", "Satisfactory-Spielstand (*.sav)|*.sav", "Sauvegarde Satisfactory (*.sav)|*.sav"),
        ["save.loaded"] = ("Loaded {0}: {1} unlocked recipes, Tier {2}.", "{0} geladen: {1} freigeschaltete Rezepte, Stufe {2}.", "{0} chargée : {1} recettes débloquées, palier {2}."),
        ["save.error"] = ("Couldn't read save: {0}", "Spielstand konnte nicht gelesen werden: {0}", "Impossible de lire la sauvegarde : {0}"),
        ["save.unsupported"] = ("No unlocked recipe list found — unsupported save version?", "Keine Liste freigeschalteter Rezepte gefunden – nicht unterstützte Spielstandversion?", "Aucune liste de recettes débloquées — version de sauvegarde non prise en charge ?"),
        ["status.downloadingData"] = ("Downloading recipes from satisfactory.wiki.gg…", "Rezepte werden von satisfactory.wiki.gg geladen…", "Téléchargement des recettes depuis satisfactory.wiki.gg…"),
        ["status.downloadingIcons"] = ("Downloading icons… {0}", "Symbole werden geladen… {0}", "Téléchargement des icônes… {0}"),
        ["status.updated"] = ("Updated: {0} recipes, {1} icons.", "Aktualisiert: {0} Rezepte, {1} Symbole.", "Mis à jour : {0} recettes, {1} icônes."),
        ["status.updateFailed"] = ("Update failed: {0}", "Aktualisierung fehlgeschlagen: {0}", "Échec de la mise à jour : {0}"),
        ["status.iconsDownloaded"] = ("Downloaded {0} icons from the wiki.", "{0} Symbole aus dem Wiki geladen.", "{0} icônes téléchargées depuis le wiki."),
        ["status.iconsFailed"] = ("Icons unavailable: {0}", "Symbole nicht verfügbar: {0}", "Icônes indisponibles : {0}"),

        // left panel
        ["grp.targets"] = ("What to produce (per minute)", "Was produziert werden soll (pro Minute)", "À produire (par minute)"),
        ["btn.addProduct"] = ("+ Add product", "+ Produkt hinzufügen", "+ Ajouter un produit"),
        ["grp.recipeSel"] = ("Recipe selection", "Rezeptauswahl", "Choix des recettes"),
        ["opt.myPicks"] = ("My picks (defaults + swaps in the table)", "Meine Auswahl (Standard + Tausch in der Tabelle)", "Mes choix (par défaut + échanges dans le tableau)"),
        ["opt.minimal"] = ("Minimal resources — find the best recipe mix at the current tech level (scarce ores weigh more). Recipes you swap in the table stay pinned.",
                           "Minimale Ressourcen – beste Rezeptkombination auf der aktuellen Techstufe finden (seltene Erze zählen mehr). In der Tabelle getauschte Rezepte bleiben fixiert.",
                           "Ressources minimales — trouve la meilleure combinaison de recettes au niveau technologique actuel (les minerais rares pèsent plus). Les recettes échangées dans le tableau restent fixées."),
        ["btn.clearPins"] = ("Clear pinned / swapped recipes", "Fixierte / getauschte Rezepte zurücksetzen", "Réinitialiser les recettes fixées / échangées"),
        ["grp.tech"] = ("Technology break point", "Technologiestand", "Niveau technologique"),
        ["tier"] = ("Tier {0}", "Stufe {0}", "Palier {0}"),
        ["chk.alts"] = ("Include alternate recipes (Hard Drives)", "Alternative Rezepte einbeziehen (Festplatten)", "Inclure les recettes alternatives (disques durs)"),
        ["chk.mam"] = ("Include MAM research recipes", "MAM-Forschungsrezepte einbeziehen", "Inclure les recettes de recherche M.A.M."),
        ["grp.nodes"] = ("Resource nodes you have", "Deine Ressourcenvorkommen", "Vos gisements de ressources"),
        ["nodes.help"] = ("Count your nodes by purity (pure ones get used first). Blank = no node limit, assume normal. Limit /min caps a resource, e.g. belt throughput.",
                          "Vorkommen nach Reinheit zählen (reine werden zuerst genutzt). Leer = keine Begrenzung, normal angenommen. Limit /min begrenzt eine Ressource, z. B. Förderbanddurchsatz.",
                          "Comptez vos gisements par pureté (les purs sont utilisés en premier). Vide = pas de limite, normal supposé. Limite /min plafonne une ressource, ex. débit du convoyeur."),
        ["col.limit"] = ("Limit", "Limit", "Limite"),
        ["col.pure"] = ("Pure", "Rein", "Pur"),
        ["col.norm"] = ("Norm", "Norm.", "Norm."),
        ["col.imp"] = ("Imp", "Unrein", "Impur"),
        ["col.resource"] = ("Resource", "Ressource", "Ressource"),
        ["tip.untick"] = ("Untick if you can't reach this resource yet", "Abwählen, wenn du diese Ressource noch nicht erreichen kannst", "Décochez si vous ne pouvez pas encore accéder à cette ressource"),
        ["needsTier"] = ("  (needs T{0})", "  (benötigt S{0})", "  (requiert P{0})"),
        ["grp.extraction"] = ("Extraction", "Abbau", "Extraction"),
        ["lbl.miner"] = ("Miner", "Miner", "Foreuse"),
        ["lbl.clock"] = ("Clock speed", "Taktrate", "Fréquence"),
        ["grp.rounding"] = ("Rounding (traced back to the miners)", "Rundung (bis zu den Minern zurückverfolgt)", "Arrondi (remonté jusqu'aux foreuses)"),
        ["mode.exact"] = ("Exact — fractional machines / underclock", "Exakt – anteilige Maschinen / heruntertakten", "Exact — machines fractionnaires / sous-cadencement"),
        ["mode.steady"] = ("Steady rate wins — overproduce. Every machine and miner rounded up at 100%; output ≥ target, extra backs up.",
                           "Konstante Rate gewinnt – Überproduktion. Jede Maschine und jeder Miner wird bei 100 % aufgerundet; Ausstoß ≥ Ziel, Überschuss staut sich.",
                           "Débit constant — surproduction. Chaque machine et foreuse arrondie au supérieur à 100 % ; production ≥ objectif, le surplus s'accumule."),
        ["mode.noclog"] = ("No clog wins — underproduce. Miners rounded down, whole chain throttled to fit; nothing ever backs up.",
                           "Kein Stau gewinnt – Unterproduktion. Miner werden abgerundet, die ganze Kette gedrosselt; nichts staut sich.",
                           "Aucun blocage — sous-production. Foreuses arrondies à l'inférieur, toute la chaîne est ralentie ; rien ne s'accumule."),

        // results
        ["summary"] = ("{0} machines   ·   {1:0.#} MW", "{0} Maschinen   ·   {1:0.#} MW", "{0} machines   ·   {1:0.#} MW"),
        ["summary.withExtractors"] = ("{0} machines (incl. {1} miners/extractors)   ·   {2:0.#} MW", "{0} Maschinen (inkl. {1} Miner/Abbaugeräte)   ·   {2:0.#} MW", "{0} machines (dont {1} foreuses/extracteurs)   ·   {2:0.#} MW"),
        ["chk.countExtractors"] = ("Count miners & extractors", "Miner & Abbaugeräte mitzählen", "Compter foreuses & extracteurs"),
        ["tab.table"] = ("Table", "Tabelle", "Tableau"),
        ["tab.tree"] = ("Production tree", "Produktionsbaum", "Arbre de production"),
        ["lbl.zoom"] = ("Zoom", "Zoom", "Zoom"),
        ["btn.fit"] = ("Fit", "Einpassen", "Ajuster"),
        ["hint.tree"] = ("Ctrl + wheel to zoom · hover a box to show only its links · dashed = loop", "Strg + Mausrad zum Zoomen · Box überfahren zeigt nur ihre Verbindungen · gestrichelt = Schleife", "Ctrl + molette pour zoomer · survolez une case pour n'afficher que ses liens · pointillés = boucle"),
        ["tab.totals"] = ("Machine totals", "Maschinen gesamt", "Total des machines"),
        ["col.type"] = ("Type", "Typ", "Type"),
        ["kind.extractor"] = ("Miner / extractor", "Miner / Abbaugerät", "Foreuse / extracteur"),
        ["kind.production"] = ("Production", "Produktion", "Production"),
        ["node.target"] = ("Final output", "Endprodukt", "Produit final"),
        ["node.surplus"] = ("Surplus / byproduct", "Überschuss / Nebenprodukt", "Surplus / sous-produit"),
        ["tabs.plan"] = ("Plan {0}", "Plan {0}", "Plan {0}"),
        ["tabs.copy"] = ("{0} (copy)", "{0} (Kopie)", "{0} (copie)"),
        ["tabs.new"] = ("New plan tab", "Neuer Plan-Tab", "Nouvel onglet de plan"),
        ["tabs.rename"] = ("Rename…", "Umbenennen…", "Renommer…"),
        ["tabs.renameTitle"] = ("Rename plan", "Plan umbenennen", "Renommer le plan"),
        ["tabs.duplicate"] = ("Duplicate", "Duplizieren", "Dupliquer"),
        ["tabs.duplicateActive"] = ("Duplicate this plan (e.g. to try other recipes)", "Diesen Plan duplizieren (z. B. um andere Rezepte zu testen)", "Dupliquer ce plan (ex. pour essayer d'autres recettes)"),
        ["tabs.close"] = ("Close", "Schließen", "Fermer"),
        ["tabs.confirmClose"] = ("Close \"{0}\"? Its targets and recipe choices will be removed.", "\"{0}\" schließen? Ziele und Rezeptauswahl werden entfernt.", "Fermer « {0} » ? Ses objectifs et choix de recettes seront supprimés."),
        ["ok"] = ("OK", "OK", "OK"),
        ["cancel"] = ("Cancel", "Abbrechen", "Annuler"),
        ["mode.drained"] = ("Drained outputs — final products are taken away constantly (train, sink, storage), so they never back up. Each shared belt gets a splitter layout (1 splitter, or 2 in a row if allowed — see the Splitters tab) and enough supply that even the weakest product meets its target.", "Abgeführte Produkte – Endprodukte werden ständig abtransportiert (Zug, Senke, Lager) und stauen sich nie. Jedes geteilte Band erhält einen Splitter-Aufbau (1 Splitter oder 2 hintereinander, falls erlaubt – siehe Tab Splitter) und genug Zufuhr, damit selbst das schwächste Produkt sein Ziel erreicht.", "Sorties drainées — les produits finaux sont évacués en continu (train, broyeur, stockage) et ne s'accumulent jamais. Chaque convoyeur partagé reçoit un montage de répartiteurs (1 répartiteur, ou 2 à la suite si autorisé — voir l'onglet Répartiteurs) et assez d'apport pour que même le produit le plus faible atteigne son objectif."),
        ["out.headroom"] = ("Spare capacity — backs up harmlessly (not wasted)", "Reservekapazität – staut sich harmlos (keine Verschwendung)", "Capacité de réserve — s'accumule sans gaspillage"),
        ["crash"] = ("Something went wrong, but your plans are safe:\n\n{0}\n\nDetails were saved to {1}", "Etwas ist schiefgelaufen, deine Pläne sind aber sicher:\n\n{0}\n\nDetails gespeichert in {1}", "Une erreur est survenue, mais vos plans sont intacts :\n\n{0}\n\nDétails enregistrés dans {1}"),
        ["tab.splitters"] = ("Splitters", "Splitter", "Répartiteurs"),
        ["col.supply"] = ("Supply /min", "Zufuhr /min", "Apport /min"),
        ["col.extra"] = ("Extra", "Mehr", "Surplus"),
        ["col.layout"] = ("Layout (⑂n = n-way splitter)", "Aufbau (⑂n = n-Wege-Splitter)", "Montage (⑂n = répartiteur n voies)"),
        ["col.shares"] = ("Consumers: need /min (share)", "Abnehmer: Bedarf /min (Anteil)", "Consommateurs : besoin /min (part)"),
        ["split.none"] = ("Single consumer — no splitter", "Einzelner Abnehmer – kein Splitter", "Un seul consommateur — pas de répartiteur"),
        ["split.manifold"] = ("Manifold (one splitter per machine), {0} last", "Verteiler (ein Splitter pro Maschine), {0} zuletzt", "Collecteur (un répartiteur par machine), {0} en dernier"),
        ["split.hint"] = ("Every belt that feeds several consumers, with the splitter layout (1 splitter, or 2 in a row if allowed) and the supply it needs so the weakest consumer still gets its full need. 'Extra' is what greedy branches (drained outputs, rounded-up machines) pull beyond their need.", "Jedes Band mit mehreren Abnehmern, mit Splitter-Aufbau (1 Splitter oder 2 hintereinander, falls erlaubt) und der nötigen Zufuhr, damit auch der schwächste Abnehmer seinen vollen Bedarf erhält. „Mehr“ ist, was gierige Zweige (abgeführte Produkte, aufgerundete Maschinen) über ihren Bedarf hinaus ziehen.", "Chaque convoyeur alimentant plusieurs consommateurs, avec le montage de répartiteurs (1 répartiteur, ou 2 à la suite si autorisé) et l'apport nécessaire pour que le plus faible reçoive tout son besoin. « Surplus » = ce que les branches gourmandes (sorties drainées, machines arrondies) prennent en plus."),
        ["split.onlyDrained"] = ("Splitter layouts are planned in the 'Drained outputs' rounding mode. In this mode, only flows that need several parallel belts are listed.", "Splitter-Aufbauten werden im Rundungsmodus „Abgeführte Produkte“ geplant (wenn Endprodukte ständig abtransportiert werden).", "Les montages de répartiteurs sont planifiés dans le mode d'arrondi « Sorties drainées » (quand les produits finaux sont évacués en continu)."),
        ["chk.twoSplitters"] = ("Allow 2 splitters in a row (default: 1)", "2 Splitter hintereinander erlauben (Standard: 1)", "Autoriser 2 répartiteurs à la suite (par défaut : 1)"),
        ["kind.logistics"] = ("Belt / pipe part", "Band-/Rohrteil", "Pièce convoyeur / tuyau"),
        ["node.sink"] = ("Sink / storage", "Senke / Lager", "Broyeur / stockage"),
        ["split.smart"] = ("Smart splitter: {0} on normal outputs, {1} on Overflow (only gets what the machines can't take)", "Intelligenter Splitter: {0} an normalen Ausgängen, {1} an Überlauf (bekommt nur, was die Maschinen nicht aufnehmen)", "Répartiteur intelligent : {0} sur les sorties normales, {1} en Débordement (ne reçoit que ce que les machines ne prennent pas)"),
        ["split.pipe"] = ("Pipe manifold with junctions (fluids share by demand)", "Rohr-Verteiler mit Verbindungsstücken (Flüssigkeiten teilen sich nach Bedarf)", "Collecteur de tuyaux avec jonctions (les fluides se répartissent selon la demande)"),
        ["chk.endSplitter"] = ("Splitter in front of the last machine too (for looks)", "Splitter auch vor der letzten Maschine (für die Optik)", "Répartiteur aussi devant la dernière machine (esthétique)"),
        ["tip.endSplitter"] = ("The last splitter of a manifold does nothing, but keeps every machine's input looking the same. Adds one splitter per manifold to the totals.", "Der letzte Splitter eines Verteilers bewirkt nichts, sieht aber einheitlich aus. Zählt einen Splitter pro Verteiler dazu.", "Le dernier répartiteur d'un collecteur ne sert à rien mais garde un aspect uniforme. Ajoute un répartiteur par collecteur."),
        ["summary.logistics"] = ("   ·   {0} splitters, {1} mergers, {2} pipe junctions", "   ·   {0} Splitter, {1} Zusammenführer, {2} Rohrverbindungen", "   ·   {0} répartiteurs, {1} fusionneurs, {2} jonctions"),
        ["grp.belts"] = ("Belts & splitters", "Bänder & Splitter", "Convoyeurs & répartiteurs"),
        ["lbl.belt"] = ("Belt", "Band", "Convoyeur"),
        ["lbl.pipe"] = ("Pipe", "Rohr", "Tuyau"),
        ["belt.auto"] = ("Auto — best unlocked at this tier", "Auto – bestes auf dieser Stufe freigeschaltetes", "Auto — le meilleur débloqué à ce palier"),
        ["belt.current"] = ("Planning with {0} belts and {1} pipes; bigger flows are split into parallel lines.", "Geplant mit {0}-Bändern und {1}-Rohren; größere Ströme werden auf parallele Linien aufgeteilt.", "Planifié avec convoyeurs {0} et tuyaux {1} ; les flux plus grands sont répartis sur des lignes parallèles."),
        ["col.line"] = ("Line", "Linie", "Ligne"),
        ["col.belt"] = ("Belt / pipe", "Band / Rohr", "Convoyeur / tuyau"),
        ["split.lines"] = ("Too much for one belt: {0} parallel lines, each fed by its own machines", "Zu viel für ein Band: {0} parallele Linien, jede mit eigenen Maschinen", "Trop pour un convoyeur : {0} lignes parallèles, chacune alimentée par ses propres machines"),
        ["edge.belts"] = ("×{0} {1}", "×{0} {1}", "×{0} {1}"),
        ["warn.notConverged"] = ("Drained mode: this plan is very large, so the splitter/supply balancing stopped early — add a little spare supply.", "Abgeführte Produkte: Der Plan ist sehr groß, der Splitter-/Zufuhrausgleich wurde früh beendet – etwas Reserve einplanen.", "Sorties drainées : plan très grand, l'équilibrage répartiteurs/apport s'est arrêté tôt — prévoyez un peu de marge."),
        ["warn.machineOverBelt"] = ("One {0} machine needs {1}/min — more than one {2} carries. Feed each with {3} belts merged at the machine, or pick a faster belt.", "Eine {0}-Maschine braucht {1}/min – mehr als ein {2} trägt. Jede mit {3} Bändern (an der Maschine zusammengeführt) versorgen oder schnelleres Band wählen.", "Une machine {0} demande {1}/min — plus qu'un {2} ne transporte. Alimentez-la avec {3} convoyeurs fusionnés à la machine, ou choisissez un convoyeur plus rapide."),
        ["node.line"] = ("line {0}/{1}", "Linie {0}/{1}", "ligne {0}/{1}"),
        ["node.inLines"] = ("in {0} lines", "in {0} Linien", "en {0} lignes"),
        ["btn.useSave"] = ("Use save", "Spielstand nutzen", "Utiliser la sauvegarde"),
        ["tip.useSave"] = ("On: plan only with recipes unlocked in the save. Off: ignore the save (keeps it loaded) and use this tab's tier and alternate/MAM settings — quick way to see what unlocking more would give you.", "An: nur mit im Spielstand freigeschalteten Rezepten planen. Aus: Spielstand ignorieren (bleibt geladen) und Stufe/Alternativen/MAM dieses Tabs verwenden – so siehst du schnell, was weitere Freischaltungen bringen.", "Activé : planifier uniquement avec les recettes débloquées dans la sauvegarde. Désactivé : ignorer la sauvegarde (elle reste chargée) et utiliser le palier et les réglages alternatives/M.A.M. de cet onglet — pour voir vite ce que d'autres déblocages apporteraient."),
        ["warn.notSettled"] = ("Drained mode: the splitter/supply balancing didn't fully settle for this plan — add a little spare supply.", "Abgeführte Produkte: Der Splitter-/Zufuhrausgleich hat sich bei diesem Plan nicht ganz eingependelt – etwas Reserve einplanen.", "Sorties drainées : l'équilibrage répartiteurs/apport ne s'est pas complètement stabilisé pour ce plan — prévoyez un peu de marge."),
        ["tab.guards"] = ("Clog guards", "Stauschutz", "Anti-blocage"),
        ["tab.guardsCount"] = ("Clog guards ({0})", "Stauschutz ({0})", "Anti-blocage ({0})"),
        ["tab.guardsWarn"] = ("⚠ Clog guards ({0} required)", "⚠ Stauschutz ({0} nötig)", "⚠ Anti-blocage ({0} requis)"),
        ["tab.guardsMixed"] = ("⚠ Clog guards ({0} required, {1} resolved)", "⚠ Stauschutz ({0} nötig, {1} gelöst)", "⚠ Anti-blocage ({0} requis, {1} résolus)"),
        ["tab.guardsResolved"] = ("✓ Clog guards (all {0} resolved)", "✓ Stauschutz (alle {0} gelöst)", "✓ Anti-blocage (les {0} résolus)"),
        ["guard.hint"] = ("Machines with several outputs stop completely when ANY output backs up. Every overflow needs somewhere that never fills: an AWESOME Sink or generators (a box fills up, and an output isn't guaranteed to be taken). What processing makes is an overflow too; it carries on in its own card below.", "Maschinen mit mehreren Ausgängen stehen still, sobald EIN Ausgang staut. Jeder Überlauf braucht ein Ziel, das nie voll wird: eine AWESOME-Senke oder Generatoren. Was die Verarbeitung macht, ist auch ein Überlauf; es geht in einer eigenen Karte darunter weiter.", "Les machines à plusieurs sorties s'arrêtent dès qu'UNE sortie bloque. Chaque débordement doit aller où rien ne se remplit : un Puits GÉNIAL ou des générateurs. Ce que produit le traitement est aussi un débordement ; il continue dans sa propre carte ci-dessous."),
        ["guard.col.machine"] = ("Machines", "Maschinen", "Machines"),
        ["guard.col.output"] = ("Output", "Ausgang", "Sortie"),
        ["guard.col.level"] = ("Need", "Bedarf", "Besoin"),
        ["guard.col.device"] = ("Guard", "Schutz", "Protection"),
        ["guard.col.where"] = ("Where / how", "Wo / wie", "Où / comment"),
        ["guard.required"] = ("Required", "Nötig", "Requis"),
        ["guard.recommended"] = ("Recommended", "Empfohlen", "Recommandé"),
        ["guard.smart"] = ("Smart splitter (Overflow)", "Intelligenter Splitter (Überlauf)", "Répartiteur intelligent (Débordement)"),
        ["guard.valve"] = ("Junction + valve", "Verbindungsstück + Ventil", "Jonction + vanne"),
        ["guard.smartHow"] = ("Right after the {0} output belt: {1} on a normal output, Overflow to your sink/storage (≈{2:0.##}/min spills).", "Direkt am Ausgangsband der {0}: {1} an einen normalen Ausgang, Überlauf zu deiner Senke/deinem Lager (≈{2:0.##}/min laufen über).", "Juste après le convoyeur de sortie des {0} : {1} sur une sortie normale, Débordement vers votre broyeur/stockage (≈{2:0.##}/min débordent)."),
        ["guard.valveHow"] = ("Right after the {0} output pipe: a junction; on the branch to {1} a valve set to {2:0.##} m³/min, the other branch to your sink/storage (≈{3:0.##} m³/min spills).", "Direkt am Ausgangsrohr der {0}: ein Verbindungsstück; im Zweig zu {1} ein Ventil auf {2:0.##} m³/min, der andere Zweig zu deiner Senke/deinem Lager (≈{3:0.##} m³/min laufen über).", "Juste après le tuyau de sortie des {0} : une jonction ; sur la branche vers {1} une vanne réglée à {2:0.##} m³/min, l'autre branche vers votre broyeur/stockage (≈{3:0.##} m³/min débordent)."),
        ["guard.recommendedWhy"] = ("Normally nothing spills — it protects the machines if {0} backs up.", "Normalerweise läuft nichts über – schützt die Maschinen, falls sich {0} staut.", "Normalement rien ne déborde — protège les machines si {0} se bloque."),
        ["guard.perLine"] = ("One per belt line ({0} lines).", "Eine pro Bandlinie ({0} Linien).", "Une par ligne ({0} lignes)."),
        ["guard.badge"] = ("overflow", "Überlauf", "débordement"),
        ["guard.badgeTip"] = ("Needs an overflow guard on: {0}. See the Clog guards tab.", "Braucht Stauschutz an: {0}. Siehe Tab Stauschutz.", "Protection anti-blocage requise sur : {0}. Voir l'onglet Anti-blocage."),
        ["warn.clog"] = ("{0} machine output(s) will clog without an overflow — see the Clog guards tab.", "{0} Maschinenausgang/-ausgänge staut sich ohne Überlauf – siehe Tab Stauschutz.", "{0} sortie(s) de machine va/vont se bloquer sans débordement — voir l'onglet Anti-blocage."),
        ["summary.valves"] = (", {0} valves", ", {0} Ventile", ", {0} vannes"),
        ["guard.routeAway"] = ("Route it all away", "Komplett wegleiten", "Tout évacuer"),
        ["guard.allAwayHow"] = ("Nothing in the plan uses it: send the whole {0} output straight to your sink/storage (≈{1:0.##} {2}). If it has nowhere to go, the machines stop.", "Nichts im Plan verwendet es: den gesamten Ausgang der {0} direkt zu deiner Senke/deinem Lager leiten (≈{1:0.##} {2}). Ohne Abfluss stoppen die Maschinen.", "Rien dans le plan ne l'utilise : envoyez toute la sortie des {0} vers votre broyeur/stockage (≈{1:0.##} {2}). Sans issue, les machines s'arrêtent."),
        ["tab.layout"] = ("Layout", "Layout", "Plan d'usine"),
        ["btn.exportPng"] = ("Export PNG…", "PNG exportieren…", "Exporter PNG…"),
        ["btn.exportCsv"] = ("Export CSV…", "CSV exportieren…", "Exporter CSV…"),
        ["btn.exportBp"] = ("Export blueprints…", "Blaupausen exportieren…", "Exporter les plans…"),
        ["tip.exportBp"] = ("Writes the layout as game blueprints (one per tile, \"<tab> r1c1\" …) into a folder you pick — normally your session's folder under SaveGames\\blueprints. Needs Node.js installed.", "Schreibt das Layout als Spiel-Blaupausen (eine pro Kachel, \"<Tab> r1c1\" …) in einen Ordner deiner Wahl — normalerweise den Ordner deines Spielstands unter SaveGames\\blueprints. Benötigt Node.js.", "Écrit le plan en plans de jeu (un par tuile, « <onglet> r1c1 »…) dans le dossier choisi — normalement celui de ta partie sous SaveGames\\blueprints. Nécessite Node.js."),
        ["bp.needTile"] = ("Pick a blueprint size (Mk2 / Mk3) first: blueprints are written per tile.", "Wähle zuerst eine Blaupausengröße (Mk2 / Mk3): Blaupausen werden pro Kachel geschrieben.", "Choisis d'abord une taille de plan (Mk2 / Mk3) : les plans sont écrits par tuile."),
        ["bp.noNode"] = ("Writing blueprints needs Node.js, and it wasn't found.\n\nOpen nodejs.org to download it? (Restart this app after installing.)", "Zum Schreiben von Blaupausen wird Node.js benötigt, es wurde nicht gefunden.\n\nnodejs.org zum Herunterladen öffnen? (Danach diese App neu starten.)", "L'écriture des plans nécessite Node.js, introuvable.\n\nOuvrir nodejs.org pour le télécharger ? (Redémarre l'application après l'installation.)"),
        ["bp.noWriter"] = ("The blueprint writer wasn't found: {0}", "Der Blaupausen-Schreiber wurde nicht gefunden: {0}", "Le générateur de plans est introuvable : {0}"),
        ["bp.pickFolder"] = ("Pick the blueprint folder (your session's folder under SaveGames\\blueprints)", "Blaupausen-Ordner wählen (Ordner deines Spielstands unter SaveGames\\blueprints)", "Choisis le dossier des plans (celui de ta partie sous SaveGames\\blueprints)"),
        ["bp.noBase"] = ("There's no blueprint made in game in \"{0}\".\n\nBlueprints need your session's details: save any blueprint in game into this folder first, then export.", "In \"{0}\" liegt keine im Spiel erstellte Blaupause.\n\nBlaupausen brauchen die Daten deines Spielstands: speichere zuerst im Spiel irgendeine Blaupause in diesen Ordner.", "Aucun plan créé en jeu dans « {0} ».\n\nLes plans ont besoin des infos de ta partie : enregistre d'abord n'importe quel plan en jeu dans ce dossier."),
        ["bp.writing"] = ("Writing blueprints…", "Blaupausen werden geschrieben…", "Écriture des plans…"),
        ["bp.checkNode"] = ("Checking for Node.js…", "Node.js wird gesucht…", "Recherche de Node.js…"),
        ["bp.installing"] = ("First export: installing the blueprint writer (npm)…", "Erster Export: Blaupausen-Schreiber wird installiert (npm)…", "Premier export : installation du générateur de plans (npm)…"),
        ["bp.installFailed"] = ("The blueprint writer couldn't be installed (it needs npm and the network): {0}\nThe \"full\" build of the app has everything built in and needs neither.", "Der Blaupausen-Schreiber konnte nicht installiert werden (braucht npm und Netzwerk): {0}\nDie „Voll“-Version der App enthält alles und braucht beides nicht.", "Impossible d'installer le générateur de plans (npm et réseau requis) : {0}\nLa version « complète » de l'application contient tout et n'en a pas besoin."),
        ["bp.progress"] = ("{0} / {1} blueprints written", "{0} / {1} Blaupausen geschrieben", "{0} / {1} plans écrits"),
        ["bp.done"] = ("{0} blueprints written to {1}", "{0} Blaupausen nach {1} geschrieben", "{0} plans écrits dans {1}"),
        ["bp.summary"] = ("{0} blueprints written to:\n{1}\n\n{2} belts / pipes between tiles need joining by hand — see \"wiring.txt\".\n(Session details taken from {3})", "{0} Blaupausen geschrieben nach:\n{1}\n\n{2} Bänder / Rohre zwischen Kacheln von Hand verbinden — siehe \"wiring.txt\".\n(Spielstanddaten aus {3})", "{0} plans écrits dans :\n{1}\n\n{2} tapis / tuyaux entre tuiles à relier à la main — voir « wiring.txt ».\n(Infos de partie prises de {3})"),
        ["bp.wiringHead"] = ("{0}: belts / pipes to join by hand between tiles (east, north from the south-west corner)", "{0}: Bänder / Rohre zwischen Kacheln von Hand verbinden (Ost, Nord ab der Südwestecke)", "{0} : tapis / tuyaux à relier à la main entre tuiles (est, nord depuis le coin sud-ouest)"),
        ["lbl.floors"] = ("Floors:", "Stockwerke:", "Étages :"),
        ["lbl.showFloor"] = ("Show:", "Zeigen:", "Afficher :"),
        ["floor.all"] = ("All", "Alle", "Tous"),
        ["layout.openAbove"] = ("open to the sky ({0} below reaches through)", "offen nach oben ({0} darunter ragt durch)", "ouvert vers le ciel ({0} en dessous traverse)"),
        ["lbl.blueprint"] = ("Blueprint", "Blaupause", "Plan"),
        ["status.floor"] = ("Floor {0} of {1}: placing machines and routing belts", "Etage {0} von {1}: Maschinen platzieren, Bänder verlegen", "Étage {0} sur {1} : placement et câblage"),
        ["status.route"] = ("Placing machines and routing belts", "Maschinen platzieren, Bänder verlegen", "Placement et câblage"),
        ["status.reroute"] = ("Some belts didn't fit: making more room around the machines and routing again", "Einige Bänder passten nicht: mehr Platz um die Maschinen, neu verlegen", "Certains convoyeurs ne passaient pas : plus d'espace autour des machines, nouveau câblage"),
        ["status.floorOf"] = ("Floor {0} of {1}", "Etage {0} von {1}", "Étage {0} sur {1}"),
        ["btn.advanced"] = ("⚙ Advanced ▾", "⚙ Erweitert ▾", "⚙ Avancé ▾"),
        ["guard.col.how"] = ("How to process", "Verarbeitung", "Traitement"),
        ["lbl.legend"] = ("Legend", "Legende", "Légende"),
        ["kpi.machines"] = ("Machines", "Maschinen", "Machines"),
        ["kpi.machinesSub"] = ("incl. {0} extractors", "inkl. {0} Förderanlagen", "dont {0} extracteurs"),
        ["kpi.machinesNoExt"] = ("plus {0} extractors", "plus {0} Förderanlagen", "plus {0} extracteurs"),
        ["kpi.power"] = ("Power", "Strom", "Énergie"),
        ["kpi.powerSub"] = ("used at 100% clock", "Verbrauch bei 100 % Takt", "consommée à 100 %"),
        ["kpi.powerGen"] = ("net; generators make {0:0} MW", "netto; Generatoren liefern {0:0} MW", "net ; les générateurs font {0:0} MW"),
        ["kpi.inputs"] = ("Raw inputs /min", "Rohstoffe /min", "Ressources /min"),
        ["kpi.clog"] = ("Clog guards", "Stauschutz", "Anti-blocage"),
        ["kpi.clogOpen"] = ("{0} required", "{0} nötig", "{0} requis"),
        ["kpi.clogOpenSub"] = ("{0} resolved; see Clog guards", "{0} gelöst; siehe Stauschutz", "{0} résolus ; voir Anti-blocage"),
        ["kpi.clogAll"] = ("All resolved", "Alle gelöst", "Tout résolu"),
        ["kpi.clogAllSub"] = ("{0} overflows end somewhere safe", "{0} Überläufe enden sicher", "{0} débordements finissent en lieu sûr"),
        ["kpi.clogNone"] = ("None needed", "Keiner nötig", "Aucun requis"),
        ["kpi.clogNoneSub"] = ("no multi-output machine can back up", "keine Maschine mit mehreren Ausgängen staut", "aucune machine à sorties multiples ne bloque"),
        ["hdr.overflow"] = ("Overflow processing", "Überlaufverarbeitung", "Traitement des débordements"),
        ["clog.status.good"] = ("✓ Safe", "✓ Sicher", "✓ Sûr"),
        ["clog.status.next"] = ("→ continues below", "→ geht unten weiter", "→ suite ci-dessous"),
        ["clog.status.warn"] = ("⚠ Will clog when full", "⚠ Staut, wenn voll", "⚠ Bloquera une fois plein"),
        ["clog.status.info"] = ("Recommended", "Empfohlen", "Recommandé"),
        ["hint.overflowRow"] = ("Processes an overflow: change it in Clog guards (how to process).", "Verarbeitet einen Überlauf: nur unter Stauschutz änderbar (Verarbeitung).", "Traite un débordement : à modifier dans Anti-blocage (traitement)."),
        ["tip.clogHow"] = ("What happens to the surplus. Only an AWESOME Sink or generators never fill up (a box fills, and an output isn't guaranteed to be taken). More machines can turn it into something else, but that product is an overflow too and gets its own row to deal with; one of this plan's products can merge into its output through a smart splitter with a sink on Overflow.", "Was mit dem Überschuss passiert: Überlauf in eine Kiste (jemand muss sie leeren), Überlauf in eine AWESOME-Senke, oder ein paar Maschinen mehr machen etwas anderes daraus (das Produkt geht zur Ausgabe dieses Gegenstands). Mit den letzten beiden läuft die Fabrik unbegrenzt allein.", "Ce que devient le surplus : débordement dans une caisse (à vider), débordement dans un Puits GÉNIAL, ou quelques machines de plus en font autre chose (le produit rejoint la sortie de cet objet). Les deux derniers laissent l'usine tourner seule indéfiniment."),
        ["clog.box"] = ("Overflow into a box (fills up — not safe)", "Überlauf in eine Kiste (wird voll — nicht sicher)", "Débordement dans une caisse (se remplit — pas sûr)"),
        ["clog.keep"] = ("Keep as is (machines use all of it)", "So lassen (Maschinen verbrauchen alles)", "Laisser tel quel (les machines utilisent tout)"),
        ["clog.gen"] = ("Burn in {0} ({1:0.#}/min each, {2:0} MW)", "In {0} verbrennen ({1:0.#}/min je, {2:0} MW)", "Brûler dans {0} ({1:0.#}/min chacun, {2:0} MW)"),
        ["clog.merge"] = ("Merge into the {0} output (smart splitter, Overflow to an AWESOME Sink)", "In die {0}-Ausgabe einspeisen (intelligenter Teiler, Überlauf in eine AWESOME-Senke)", "Fusionner dans la sortie {0} (répartiteur intelligent, débordement vers un Puits GÉNIAL)"),
        ["clog.chain"] = ("{2:0.##} {3} {0}: made from the surplus by {1} — it's an overflow too and needs its own way out.", "{2:0.##} {3} {0}: von {1} aus dem Überschuss gemacht — auch ein Überlauf, braucht einen eigenen Ausweg.", "{2:0.##} {3} {0} : fait du surplus par {1} — c'est aussi un débordement, il lui faut sa propre sortie."),
        ["clog.boxHow"] = ("Now it overflows into a box: once full, it backs up and the whole chain stops.", "Jetzt Überlauf in eine Kiste: ist sie voll, staut es und die ganze Kette steht.", "Pour l'instant dans une caisse : une fois pleine, tout se bloque."),
        ["clog.genHow"] = ("The overflow is burnt in generators (they never fill up).", "Der Überlauf wird in Generatoren verbrannt (die werden nie voll).", "Le débordement est brûlé dans des générateurs (ils ne se remplissent jamais)."),
        ["clog.mergeHow"] = ("Through a smart splitter first: one output merges into that product's output, Overflow goes to an AWESOME Sink — a full output can't back it up.", "Erst durch einen intelligenten Teiler: ein Ausgang in die Ausgabe des Produkts, Überlauf in eine AWESOME-Senke — eine volle Ausgabe staut nichts.", "D'abord un répartiteur intelligent : une sortie rejoint la sortie du produit, le débordement va dans un Puits GÉNIAL — une sortie pleine ne bloque rien."),
        ["item.overflow"] = ("{0} (overflow)", "{0} (Überlauf)", "{0} (débordement)"),
        ["clog.sink"] = ("Overflow into an AWESOME Sink", "Überlauf in eine AWESOME-Senke", "Débordement dans un Puits GÉNIAL"),
        ["clog.recipe"] = ("→ {0} ({1} → {2})", "→ {0} ({1} → {2})", "→ {0} ({1} → {2})"),
        ["clog.sinkHow"] = ("The overflow goes straight into an AWESOME Sink (smart splitter Overflow).", "Der Überlauf geht direkt in eine AWESOME-Senke (intelligenter Teiler, Überlauf).", "Le débordement va directement dans un Puits GÉNIAL (répartiteur intelligent, débordement)."),
        ["clog.recipeHow"] = ("The surplus is used up by {0}; what it makes is a new overflow (the card below).", "Der Überschuss wird von {0} verbraucht; was dabei entsteht, ist ein neuer Überlauf (Karte darunter).", "Le surplus est utilisé par {0} ; ce qu'il produit est un nouveau débordement (carte ci-dessous)."),
        ["out.sink"] = ("Surplus (overflow into an AWESOME Sink)", "Überschuss (Überlauf in eine AWESOME-Senke)", "Surplus (débordement dans un Puits GÉNIAL)"),
        ["loop.title"] = ("Plastic + rubber: recycling loop?", "Kunststoff + Gummi: Recycling-Schleife?", "Plastique + caoutchouc : boucle de recyclage ?"),
        ["loop.ask"] = ("This plan makes only plastic and rubber, and your recipes allow the recycling loop:\n\nCrude oil → Heavy Oil Residue (alt) → Diluted Packaged Fuel (alt, with packaged water) → unpackaged fuel → Recycled Plastic / Recycled Rubber, turning each into the other. About 80 plastic + rubber per 30 crude oil (about 40 with the plain recipes).\n\nIt needs a one-off starting stock: some plastic and rubber in the recycling refineries and some empty canisters in the packagers. Smart splitters feed the loop first and only send the surplus to the output, so the loop never runs dry.\n\nYes: use the recycling loop.\nNo: use the plain recipes (simpler, less per crude oil).",
            "Dieser Plan stellt nur Kunststoff und Gummi her, und deine Rezepte erlauben die Recycling-Schleife:\n\nRohöl → Schweröl-Rückstand (Alt.) → Verdünnter verpackter Treibstoff (Alt., mit verpacktem Wasser) → entpackter Treibstoff → Recycelter Kunststoff / Recycelter Gummi, die sich gegenseitig herstellen. Etwa 80 Kunststoff + Gummi pro 30 Rohöl (etwa 40 mit den normalen Rezepten).\n\nSie braucht einmalig einen Startbestand: etwas Kunststoff und Gummi in den Recycling-Raffinerien und leere Kanister in den Verpackern. Intelligente Teiler versorgen zuerst die Schleife und schicken nur den Überschuss zur Ausgabe, so läuft sie nie leer.\n\nJa: Recycling-Schleife verwenden.\nNein: normale Rezepte (einfacher, weniger pro Rohöl).",
            "Ce plan ne produit que du plastique et du caoutchouc, et vos recettes permettent la boucle de recyclage :\n\nPétrole brut → Résidu de pétrole lourd (alt.) → Carburant conditionné dilué (alt., avec de l'eau conditionnée) → carburant déconditionné → Plastique recyclé / Caoutchouc recyclé, chacun produisant l'autre. Environ 80 plastique + caoutchouc pour 30 pétrole brut (environ 40 avec les recettes normales).\n\nIl faut un stock de départ unique : un peu de plastique et de caoutchouc dans les raffineries de recyclage et des bidons vides dans les conditionneurs. Des répartiteurs intelligents servent la boucle d'abord et n'envoient que le surplus à la sortie : la boucle ne s'arrête jamais.\n\nOui : utiliser la boucle de recyclage.\nNon : recettes normales (plus simple, moins par pétrole brut)."),
        ["loop.seed"] = ("Recycling loop: before starting, put some plastic and rubber in the recycling refineries and empty canisters in the packagers; the loop keeps them topped up after that.", "Recycling-Schleife: vor dem Start etwas Kunststoff und Gummi in die Recycling-Raffinerien und leere Kanister in die Verpacker legen; danach füllt die Schleife sie selbst nach.", "Boucle de recyclage : avant de démarrer, mettez du plastique et du caoutchouc dans les raffineries de recyclage et des bidons vides dans les conditionneurs ; la boucle les réapprovisionne ensuite."),
        ["lbl.timeLimit"] = ("Time limit for the layout", "Zeitlimit für das Layout", "Temps limite pour la disposition"),
        ["tip.timeLimit"] = ("More time gives big plans a better chance of a routed layout. With a short limit, large plans (many machine types, several floors) will likely run out of time and get the row layout instead.", "Mehr Zeit gibt großen Plänen eine bessere Chance auf ein verlegtes Layout. Bei kurzem Limit reicht die Zeit für große Pläne (viele Maschinentypen, mehrere Etagen) wahrscheinlich nicht, und sie bekommen das Reihen-Layout.", "Plus de temps donne aux grands plans une meilleure chance d'obtenir une disposition câblée. Avec une limite courte, les grands plans (beaucoup de types de machines, plusieurs étages) manqueront probablement de temps et recevront la disposition en rangées."),
        ["layout.left"] = ("{0} left (limit {1})", "noch {0} (Limit {1})", "{0} restant (limite {1})"),
        ["layout.overtime"] = ("Time's up, finishing…", "Zeit abgelaufen, wird abgeschlossen…", "Temps écoulé, finalisation…"),
        ["layout.fallback"] = ("If no routed layout is found in time, you get the simple row layout instead (machines in rows, longer belts, more space). To try again with more time, raise the limit under ⚙ Advanced and press “Lay out again”.", "Wird rechtzeitig kein verlegtes Layout gefunden, gibt es stattdessen das einfache Reihen-Layout (Maschinen in Reihen, längere Bänder, mehr Platz). Für einen neuen Versuch das Limit unter ⚙ Erweitert erhöhen und „Neu anordnen“ klicken.", "Si aucune disposition câblée n'est trouvée à temps, vous obtenez la disposition simple en rangées (machines en rangées, convoyeurs plus longs, plus de place). Pour réessayer, augmentez la limite dans ⚙ Avancé et cliquez sur « Recalculer »."),
        ["status.stack"] = ("Stacking {0} congested corridor(s)", "{0} enge Korridore stapeln", "Empilement de {0} couloir(s) encombré(s)"),
        ["status.twostage"] = ("Retrying: short lines first, long lines on upper levels", "Neuer Versuch: kurze Linien zuerst, lange oben", "Nouvel essai : lignes courtes d'abord, longues en hauteur"),
        ["status.compact"] = ("Compacting (closing up empty space)", "Verdichten (Lücken schließen)", "Compactage (réduction des vides)"),
        ["status.narrow"] = ("Trying tighter machine groups", "Versuche engere Maschinengruppen", "Essai de groupes de machines plus serrés"),
        ["chk.backUp"] = ("Intermediates may back up (no overproduction when there are no byproducts)", "Zwischenprodukte dürfen sich stauen (keine Überproduktion ohne Nebenprodukte)", "Les produits intermédiaires peuvent s'accumuler (pas de surproduction sans sous-produits)"),
        ["tip.backUp"] = ("An intermediate used only by machines may back up on its belt: its splitters then balance by themselves, so no extra supply is planned. Not for items whose makers have a byproduct — a backed-up byproduct stops the machine and production drops.", "Ein Zwischenprodukt, das nur Maschinen nutzen, darf sich auf dem Band stauen: die Splitter gleichen dann selbst aus, keine Extrazufuhr. Nicht, wenn seine Hersteller ein Nebenprodukt haben — ein gestautes Nebenprodukt stoppt die Maschine.", "Un produit intermédiaire utilisé seulement par des machines peut s'accumuler : les répartiteurs s'équilibrent seuls, aucun apport supplémentaire. Pas si ses producteurs ont un sous-produit — un sous-produit bloqué arrête la machine."),
        ["status.steps"] = ("Trying floors split by production step", "Versuche Etagen nach Produktionsschritt", "Essai d'étages par étape de production"),
        ["status.rows"] = ("Falling back to the row layout", "Weiche auf das Reihen-Layout aus", "Repli sur la disposition en rangées"),
        ["status.elapsed"] = ("{0} s so far", "bisher {0} s", "{0} s écoulées"),
        ["layout.handTag"] = ("place by hand", "von Hand", "à la main"),
        ["bp.off"] = ("No tiles", "Keine Kacheln", "Sans tuiles"),
        ["bp.mk2"] = ("Mk2 (5×5)", "Mk2 (5×5)", "Mk2 (5×5)"),
        ["bp.mk3"] = ("Mk3 (6×6)", "Mk3 (6×6)", "Mk3 (6×6)"),
        ["chk.bigTank"] = ("Industrial fluid buffers", "Industrielle Flüssigkeitspuffer", "Tampons de fluide industriels"),
        ["tip.bigTank"] = ("Fluid input / output boxes use the Industrial Fluid Buffer (2400 m³, about 12 m across) instead of the Fluid Buffer (400 m³, 4 m). Layouts get bigger (plastic: 4 -> 7 blueprints when measured).", "Flüssigkeits-Ein-/Ausgänge nutzen den industriellen Flüssigkeitspuffer (2400 m³, ca. 12 m breit) statt des Flüssigkeitspuffers (400 m³, 4 m). Layouts werden größer (Kunststoff: gemessen 4 -> 7 Blaupausen).", "Les entrées / sorties de fluide utilisent le tampon de fluide industriel (2400 m³, environ 12 m) au lieu du tampon de fluide (400 m³, 4 m). Les plans grandissent (plastique : 4 -> 7 plans mesurés)."),
        ["cache.bigTank"] = ("industrial buffers", "industrielle Puffer", "tampons industriels"),
        ["hand.warn"] = ("Machines may cross tiles: blueprints may come out misplaced or clipped.\n\n• Machines across a tile border aren't in the blueprints: you place them by hand (✋ marks).\n• No safety zones by the tile borders: belts / pipes, splitters, mergers and ramps near a border may be cut off, sit off their ports or need finishing by hand (see \"join by hand\" in wiring.txt).\n• A splitter / merger may sit too close to a bend, its output twisted.\n\nIt usually saves blueprints, at the cost of more fixing by hand. Continue?", "Maschinen dürfen Kacheln überqueren: Blaupausen können verrutscht oder abgeschnitten sein.\n\n• Maschinen über einer Kachelgrenze fehlen in den Blaupausen: du baust sie von Hand (✋).\n• Keine Schutzzonen an den Grenzen: Bänder / Rohre, Splitter, Merger und Rampen nahe einer Grenze können abgeschnitten sein, neben ihren Anschlüssen sitzen oder Handarbeit brauchen (siehe \"von Hand verbinden\" in wiring.txt).\n• Ein Splitter / Merger kann zu nah an einer Kurve sitzen, sein Ausgang verdreht.\n\nSpart meist Blaupausen, kostet aber mehr Handarbeit. Fortfahren?", "Machines à cheval sur les tuiles : les plans peuvent être décalés ou tronqués.\n\n• Les machines à cheval sur une limite ne sont pas dans les plans : tu les places à la main (✋).\n• Pas de zones de sécurité aux limites : tapis / tuyaux, répartiteurs, fusionneurs et rampes près d'une limite peuvent être coupés, décalés de leurs ports ou à terminer à la main (voir « à relier à la main » dans wiring.txt).\n• Un répartiteur / fusionneur peut être trop près d'un virage, sa sortie tordue.\n\nÉconomise souvent des plans, mais demande plus de retouches. Continuer ?"),
        ["chk.byHand"] = ("Machines may cross tiles (place by hand)", "Maschinen dürfen Kacheln überqueren (von Hand platzieren)", "Machines à cheval sur les tuiles (placées à la main)"),
        ["tip.byHand"] = ("Machines may straddle a blueprint border: they're left out of the blueprints and you place them yourself. While one machine of a group sits inside a blueprint, the others line up from it; if every machine of a group is placed by hand, the group's corner sits on a foundation corner. ⚠ Belts / pipes near tile borders may be clipped or misplaced and need fixing by hand.", "Maschinen dürfen über eine Blaupausengrenze ragen: sie fehlen in den Blaupausen und werden von Hand gebaut. Steht eine Maschine der Gruppe in einer Blaupause, richten sich die anderen an ihr aus; muss die ganze Gruppe von Hand gebaut werden, liegt ihre Ecke auf einer Fundamentecke. ⚠ Bänder / Rohre nahe Kachelgrenzen können abgeschnitten oder verrutscht sein.", "Les machines peuvent chevaucher une limite de plan : elles sont retirées des plans et placées à la main. Si une machine du groupe est dans un plan, les autres s'alignent sur elle ; si tout le groupe est placé à la main, son coin est sur un coin de fondation. ⚠ Tapis / tuyaux près des limites peuvent être tronqués ou décalés."),
        ["layout.byHand"] = ("{0} machines placed by hand", "{0} Maschinen von Hand", "{0} machines placées à la main"),
        ["lbl.cached"] = ("Saved", "Gespeichert", "Enregistrés"),
        ["tip.cached"] = ("Layouts this tab has worked out, each with its plan (↩ = another plan). Pick one to bring back its plan and layout options — no recalculation.", "Von diesem Tab berechnete Layouts, jeweils mit ihrem Plan (↩ = anderer Plan). Eines wählen, um Plan und Layout-Optionen wiederherzustellen – ohne Neuberechnung.", "Plans calculés par cet onglet, chacun avec son plan de production (↩ = autre plan). En choisir un pour rétablir ce plan et ses options — sans recalcul."),
        ["btn.relayout"] = ("Lay out again", "Neu anordnen", "Recalculer"),
        ["tip.relayout"] = ("Ignore the saved layout and work it out again (replacing it).", "Gespeichertes Layout ignorieren und neu berechnen (ersetzt es).", "Ignorer le plan enregistré et le recalculer (il est remplacé)."),
        ["layout.fromCache"] = ("saved layout", "gespeichertes Layout", "plan enregistré"),
        ["cache.blueprints"] = ("{0} blueprints · ", "{0} Blaupausen · ", "{0} plans · "),
        ["cache.machines"] = ("{0} machines", "{0} Maschinen", "{0} machines"),
        ["cache.entry"] = ("{0} fl · {1}{2} · {3}{4:0} m · {5:M/d HH:mm}", "{0} Et. · {1}{2} · {3}{4:0} m · {5:d.M. HH:mm}", "{0} ét. · {1}{2} · {3}{4:0} m · {5:d/M HH:mm}"),
        ["layout.busy"] = ("Calculating layout…", "Layout wird berechnet…", "Calcul de la disposition…"),
        ["layout.copies"] = ("module: place this layout {0}× (each makes 1/{0} of the output)", "Modul: dieses Layout {0}× bauen (je 1/{0} der Menge)", "module : placer cette disposition {0}× (chacune 1/{0} de la production)"),
        ["layout.info"] = ("{0:0} × {1:0} foundations ({2:0} × {3:0} m) · {4} rows · {5} bus lanes", "{0:0} × {1:0} Fundamente ({2:0} × {3:0} m) · {4} Reihen · {5} Bus-Spuren", "{0:0} × {1:0} fondations ({2:0} × {3:0} m) · {4} rangées · {5} voies du bus"),
        ["layout.legend"] = ("Sky view, north up; one floor at a time (Show) — other floors as dashed outlines. Rows of machine groups: inputs arrive on belts south of each row (white squares = splitters), outputs leave on belts north of it (outlined squares = mergers). Each item has one vertical trunk placed next to its machines; arrows show the flow. Station boxes sit at the east end of the bottom row with a free outer side: green = inputs, violet = outputs, grey = spare/overflow. ⊕ = each group's corner anchor on a foundation corner, the rest follow at the stated spacing. Dashed with orange ends = lifted over other belts or machines (never over machines taller than 12 m). Purple square ⇅ = conveyor lift / pipe to another floor. Floors are 12 m apart, 16 m when a floor has machines taller than 11 m; buildings taller than 15 m only on the top floor. Red = clog guard (square: smart splitter overflow, diamond: valve). Sizes: satisfactory-calculator.com, heights: satisfactory.wiki.gg.", "Ein Stockwerk, Norden oben. Unterkante = Bahnhofswand: grün = Eingänge, violett = Ausgänge, grau = Überschuss. Links = Bus (eine Spur pro Gegenstand und Bandlinie). Reihen = Maschinen, von Süden per Verteiler versorgt (weiße Quadrate = Splitter), im Norden gesammelt (umrandete Quadrate = Zusammenführer). Gelb = Bänder, blau = Rohre (Punkte = Verbindungsstücke). Rot = Stauschutz (Quadrat: Splitter-Überlauf, Raute: Ventil). ⤒n = Bandlifte über n Bus-Spuren. Gebäudegrößen von satisfactory-calculator.com.", "Un seul étage, nord en haut. Bord inférieur = mur de gare : vert = entrées, violet = sorties, gris = surplus. À gauche = bus (une voie par objet et ligne). Rangées = machines, alimentées au sud par un collecteur (carrés blancs = répartiteurs), collectées au nord (carrés vides = fusionneurs). Jaune = convoyeurs, bleu = tuyaux (points = jonctions). Rouge = anti-blocage (carré : débordement, losange : vanne). ⤒n = ascenseurs au-dessus de n voies. Tailles des bâtiments : satisfactory-calculator.com."),
        ["layout.saved"] = ("Saved {0}", "{0} gespeichert", "{0} enregistré"),
        ["layout.anchor"] = ("⊕ corner anchor at foundation ({0:0}, {1:0}), then every {2:0} m", "⊕ Eck-Anker auf Fundament ({0:0}, {1:0}), dann alle {2:0} m", "⊕ ancre (coin) à la fondation ({0:0}, {1:0}), puis tous les {2:0} m"),
        ["layout.anchor2"] = ("⊕ {0} corner at foundation ({1:0}, {2:0}), then every {3:0} m", "⊕ {0}-Ecke auf Fundament ({1:0}, {2:0}), dann alle {3:0} m", "⊕ coin {0} à la fondation ({1:0}, {2:0}), puis tous les {3:0} m"),
        ["layout.belts"] = (" · belts & pipes ≈{0:0} m · up to {1} machines per row", " · Bänder & Rohre ≈{0:0} m · bis {1} Maschinen pro Reihe", " · convoyeurs & tuyaux ≈{0:0} m · jusqu'à {1} machines par rangée"),
        ["summary.scale"] = ("   ·   Actual output {0:P1} of target", "   ·   Tatsächlicher Ausstoß {0:P1} des Ziels", "   ·   Production réelle {0:P1} de l'objectif"),
        ["error"] = ("Error: {0}", "Fehler: {0}", "Erreur : {0}"),
        ["hint.production"] = ("Production — pick a different recipe in the Recipe column to swap it.", "Produktion – wähle in der Spalte Rezept ein anderes Rezept, um es zu tauschen.", "Production — choisissez une autre recette dans la colonne Recette pour l'échanger."),
        ["col.item"] = ("Item", "Gegenstand", "Objet"),
        ["col.recipe"] = ("Recipe", "Rezept", "Recette"),
        ["col.building"] = ("Building", "Gebäude", "Bâtiment"),
        ["col.machines"] = ("Machines", "Maschinen", "Machines"),
        ["col.clock"] = ("Clock", "Takt", "Fréq."),
        ["col.output"] = ("Output /min", "Ausstoß /min", "Production /min"),
        ["col.inputs"] = ("Inputs /min", "Eingänge /min", "Entrées /min"),
        ["col.goesTo"] = ("Goes to /min", "Geht an /min", "Destination /min"),
        ["col.power"] = ("Power MW", "Strom MW", "Énergie MW"),
        ["hdr.raw"] = ("Raw resources & extractors", "Rohstoffe & Abbaugeräte", "Ressources brutes & extracteurs"),
        ["col.rate"] = ("Rate /min", "Rate /min", "Débit /min"),
        ["col.extractor"] = ("Extractor", "Abbaugerät", "Extracteur"),
        ["col.count"] = ("Count", "Anzahl", "Nombre"),
        ["col.note"] = ("Note", "Hinweis", "Remarque"),
        ["tab.outputs"] = ("Outputs & byproducts", "Produkte & Nebenprodukte", "Produits & sous-produits"),
        ["col.outputItem"] = ("Output", "Produkt", "Produit"),
        ["col.perMin"] = ("/min", "/min", "/min"),
        ["tab.unlock"] = ("Unlock suggestions", "Freischalt-Vorschläge", "Déblocages suggérés"),
        ["tab.unlockCount"] = ("Unlock suggestions ({0})", "Freischalt-Vorschläge ({0})", "Déblocages suggérés ({0})"),
        ["tab.unlockWarn"] = ("⚠ Unlock suggestions", "⚠ Freischalt-Vorschläge", "⚠ Déblocages suggérés"),
        ["col.benefit"] = ("Benefit", "Nutzen", "Avantage"),
        ["col.unlockedBy"] = ("Unlocked by", "Freigeschaltet durch", "Débloqué par"),
        ["analysing"] = ("Analysing…", "Wird analysiert…", "Analyse en cours…"),
        ["analysisFailed"] = ("Analysis failed: {0}", "Analyse fehlgeschlagen: {0}", "Échec de l'analyse : {0}"),

        // plan rows
        ["alt"] = ("Alt: ", "Alt.: ", "Alt. : "),
        ["purity.Pure"] = ("Pure", "Rein", "Pur"),
        ["purity.Normal"] = ("Normal", "Normal", "Normal"),
        ["purity.Impure"] = ("Impure", "Unrein", "Impur"),
        ["goes.target"] = ("{0} target", "{0} Ziel", "{0} objectif"),
        ["import"] = ("Import", "Import", "Import"),
        ["recipe.import"] = ("📦 Import instead (made elsewhere)", "📦 Stattdessen importieren (woanders hergestellt)", "📦 Importer à la place (produit ailleurs)"),
        ["imp.label"] = ("Imported:", "Importiert:", "Importé :"),
        ["grp.imported"] = ("Imported (made elsewhere)", "Importiert (woanders hergestellt)", "Importé (produit ailleurs)"),
        ["tip.import"] = ("Items this plan doesn't make: they come in like a raw resource from elsewhere (e.g. a stand-alone plastic / rubber site). A product this factory is asked to make is never imported.", "Gegenstände, die dieser Plan nicht herstellt: sie kommen wie ein Rohstoff von woanders (z. B. eine eigene Kunststoff-/Gummi-Anlage). Ein Produkt, das diese Fabrik herstellen soll, wird nie importiert.", "Objets que cette usine ne fabrique pas : ils arrivent comme une ressource brute d'ailleurs (p. ex. un site plastique / caoutchouc dédié). Un produit que l'usine doit fabriquer n'est jamais importé."),
        ["tip.unimport"] = ("Make it in this factory again", "Wieder in dieser Fabrik herstellen", "Le refabriquer dans cette usine"),
        ["tip.importPick"] = ("Type to search, then add an imported item", "Tippen zum Suchen, dann einen importierten Gegenstand hinzufügen", "Tapez pour chercher, puis ajoutez un objet importé"),
        ["tip.productSearch"] = ("Type any part of a name (this language or English); Enter or a click adds it as a product", "Einen beliebigen Teil eines Namens tippen (diese Sprache oder Englisch); Enter oder Klick fügt es als Produkt hinzu", "Tapez une partie d'un nom (cette langue ou l'anglais) ; Entrée ou un clic l'ajoute comme produit"),
        ["note.supplied"] = ("Imported (made elsewhere, delivered like a raw resource)", "Als Rohstoff geliefert (woanders in einer Ölanlage hergestellt)", "Fourni comme ressource brute (produit ailleurs, sur un site pétrolier)"),
        ["chk.polymers"] = ("Plastic and rubber come in as inputs", "Kunststoff und Gummi als Eingang liefern", "Plastique et caoutchouc fournis en entrée"),
        ["tip.polymers"] = ("Don't make plastic / rubber in this factory (no refinery chain looping the two into each other): they arrive like raw resources. Still made when they are this plan's product.", "Kunststoff / Gummi nicht in dieser Fabrik herstellen (keine Raffineriekette, die beide ineinander verwertet): sie kommen wie Rohstoffe an. Sind sie das Produkt dieses Plans, werden sie weiter hergestellt.", "Ne pas produire plastique / caoutchouc dans cette usine (pas de chaîne de raffinerie qui les recycle l'un dans l'autre) : ils arrivent comme des ressources brutes. Toujours produits s'ils sont le produit de ce plan."),
        ["note.noRecipe"] = ("No unlocked recipe (or deficit) — supply externally", "Kein freigeschaltetes Rezept (oder Defizit) – extern liefern", "Aucune recette débloquée (ou déficit) — à fournir de l'extérieur"),
        ["why.tier"] = ("extractor needs Tier {0}", "Abbaugerät benötigt Stufe {0}", "l'extracteur requiert le palier {0}"),
        ["why.marked"] = ("marked not accessible", "als nicht erreichbar markiert", "marquée inaccessible"),
        ["note.notAccessible"] = ("Not accessible ({0}) — haul it in or change recipes", "Nicht erreichbar ({0}) – heranschaffen oder Rezepte ändern", "Inaccessible ({0}) — acheminez-la ou changez de recettes"),
        ["warn.notAccessible"] = ("{0} is needed but not accessible ({1}).", "{0} wird benötigt, ist aber nicht erreichbar ({1}).", "{0} est nécessaire mais inaccessible ({1})."),
        ["warn.overLimit"] = ("{0}: needs {1}/min but your nodes/limit give {2}/min.", "{0}: benötigt {1}/min, deine Vorkommen/Limits liefern {2}/min.", "{0} : besoin de {1}/min mais vos gisements/limites donnent {2}/min."),
        ["warn.lessThanOne"] = ("{0}: needs less than one full extractor — it is underclocked instead.", "{0}: benötigt weniger als ein volles Abbaugerät – es wird stattdessen heruntergetaktet.", "{0} : moins d'un extracteur complet nécessaire — il est sous-cadencé."),
        ["note.short"] = ("Short {0}/min — not enough nodes listed", "{0}/min fehlen – nicht genug Vorkommen angegeben", "Manque {0}/min — pas assez de gisements indiqués"),
        ["note.spare"] = ("+{0}/min spare supply (will back up)", "+{0}/min Überschuss (staut sich)", "+{0}/min en surplus (va s'accumuler)"),
        ["note.underclock"] = ("underclock so nothing backs up", "heruntertakten, damit sich nichts staut", "sous-cadencer pour éviter l'accumulation"),
        ["out.target"] = ("Target {0}/min", "Ziel {0}/min", "Objectif {0}/min"),
        ["out.actual"] = (" → actual {0}", " → tatsächlich {0}", " → réel {0}"),
        ["out.byproduct"] = ("Byproduct / surplus (sink or store)", "Nebenprodukt / Überschuss (versenken oder lagern)", "Sous-produit / surplus (à recycler ou stocker)"),
        ["warn.loop"] = ("Your recipe picks form a loop; balanced it with the optimizer using the same recipes.", "Deine Rezeptauswahl bildet eine Schleife; sie wurde mit dem Optimierer und denselben Rezepten ausgeglichen.", "Vos recettes forment une boucle ; équilibrée par l'optimiseur avec les mêmes recettes."),
        ["warn.deficit"] = ("{0}: not enough produced — import {1:0.##}/min.", "{0}: zu wenig produziert – {1:0.##}/min importieren.", "{0} : production insuffisante — importer {1:0.##}/min."),
        ["warn.noConverge"] = ("Optimizer did not converge — showing nothing.", "Der Optimierer hat keine Lösung gefunden – keine Anzeige.", "L'optimiseur n'a pas convergé — rien à afficher."),
        ["warn.cantMake"] = ("{0}: {1:0.##}/min can't be made with current tech/resources — import it.", "{0}: {1:0.##}/min können mit aktueller Technik/Ressourcen nicht hergestellt werden – importieren.", "{0} : {1:0.##}/min impossible à produire avec la technologie/ressources actuelles — à importer."),

        // unlock suggestions
        ["unlock.notPossible"] = ("Not possible at Tier {0}: {1} can't be made", "Auf Stufe {0} nicht möglich: {1} kann nicht hergestellt werden", "Impossible au palier {0} : {1} ne peut pas être produit"),
        ["unlock.untilTier"] = (" until you reach milestone Tier {0}.", ", bis du Meilenstein-Stufe {0} erreichst.", " avant d'atteindre le palier {0}."),
        ["unlock.checkResources"] = (" (check accessible resources).", " (erreichbare Ressourcen prüfen).", " (vérifiez les ressources accessibles)."),
        ["unlock.required"] = ("REQUIRED to make {0}", "ERFORDERLICH für {0}", "REQUIS pour produire {0}"),
        ["unlock.requiredSummary"] = ("Unlock the {0} REQUIRED recipe(s) to make {1}.", "Schalte die {0} ERFORDERLICHEN Rezepte frei, um {1} herzustellen.", "Débloquez la/les {0} recette(s) REQUISE(S) pour produire {1}."),
        ["unlock.saves"] = ("Optional — saves {0:P1} raw resources", "Optional – spart {0:P1} Rohstoffe", "Optionnel — économise {0:P1} de ressources"),
        ["unlock.combined"] = ("Optional — helps combined with others", "Optional – hilft in Kombination mit anderen", "Optionnel — utile combiné aux autres"),
        ["unlock.optionalSummary"] = ("Unlocking the {0} optional recipe(s) available at Tier {1} would save {2:P1} of weighted raw resources.",
                                      "Die {0} optionalen Rezepte auf Stufe {1} freizuschalten würde {2:P1} der gewichteten Rohstoffe sparen.",
                                      "Débloquer la/les {0} recette(s) optionnelle(s) disponible(s) au palier {1} économiserait {2:P1} des ressources pondérées."),
        ["unlock.nothing"] = ("Nothing to unlock — your recipes already give the best plan at Tier {0}.", "Nichts freizuschalten – deine Rezepte ergeben bereits den besten Plan auf Stufe {0}.", "Rien à débloquer — vos recettes donnent déjà le meilleur plan au palier {0}."),
    };
}
